DROP TABLE CART_ITEM IF EXISTS;
DROP TABLE CART IF EXISTS;
DROP TABLE BIKES IF EXISTS;

CREATE TABLE BIKES
(
    ID             VARCHAR(25) PRIMARY KEY,
    NAME           VARCHAR(50),
    DESCRIPTION    VARCHAR(1000),
    UNIT_PRICE     DECIMAL,
    MANUFACTURER   VARCHAR(50),
    CATEGORY       VARCHAR(50),
    CONDITION      VARCHAR(50),
    UNITS_IN_STOCK BIGINT,
    UNITS_IN_ORDER BIGINT,
    DISCONTINUED   BOOLEAN
);

CREATE TABLE CART
(
    ID VARCHAR(50) PRIMARY KEY
);

CREATE TABLE CART_ITEM
(
    ID       VARCHAR(75),
    BIKE_ID  VARCHAR(25) FOREIGN KEY REFERENCES BIKES (ID),
    CART_ID  VARCHAR(50) FOREIGN KEY REFERENCES CART (ID),
    QUANTITY BIGINT,
    CONSTRAINT CART_ITEM_BIKE PRIMARY KEY (ID, CART_ID)
);

